disabled_rules: #禁用指定的规则
 - large_tuple
 - trailing_whitespace # 空行内空格
 - trailing_newline # 尾空行
 - multiple_closures_with_trailing_closure
 - nesting
 - empty_parentheses_with_trailing_closure
 - vertical_whitespace
 

opt_in_rules: #启用指定的规则
 # - force_unwrapping
included: #执行 linting 时包含的路径。如果出现这个 `--path` 会被忽略

excluded: #执行 linting 时忽略的路径。优先级比 `included` 更高。
 - Pods
 - Modules
 - Carthage
 - Source/ExcludedFolder
 - Source/ExcludedFile.swift
  
# 可配置的规则可以通过这个配置文件来自定义
# 二进制规则可以设置它们的严格程度
force_cast: warning # 隐式
force_try:
  severity: warning # 显示

# 同时有警告和错误等级的规则，可以只设置它的警告等级
# 隐式
line_length: 400
# 可以通过一个数组同时进行隐式设置
type_body_length:
  - 300 # warning
  - 400 # error
# 或者也可以同时进行显示设置
file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 100
  error: 200

# 命名规则可以设置最小长度和最大程度的警告/错误
# 此外它们也可以设置排除在外的名字
type_name:
  min_length: 1 #只是警告
  max_length: # 警告和错误
    warning: 40
    error: 50
  excluded: iPhone #排除某个名字

identifier_name: #变量规则
  min_length: 1
  excluded: # 排除某些名字
    - id
    - URL

reporter: "xcode" # 报告类型 (xcode, json, csv, checkstyle)


