# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
inhibit_all_warnings!

target 'HARMAY' do
  
  use_frameworks!
  pod 'ThirdLib', :path => 'Modules/ThirdLib'
  pod 'HMSwifterSwift', :path => 'Modules/HMSwifterSwift'
  pod 'Request', :path => 'Modules/Request'
  pod 'Home', :path => 'Modules/Home'
  pod 'Order', :path => 'Modules/Order'
    
  pod 'BeeHive'
  pod 'SwiftLint'


end
